language: generic 
sudo: required
servives:
    - docker

before_install:
    - docker build -t arunasva/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arunasva/docker-react npm run test